project_id = "valazbmgqazykdzcwfcs"

[functions.send-push-notification]
verify_jwt = false

[functions.create-direct-conversation]
verify_jwt = true

[functions.cleanup-group-calls]
verify_jwt = false

[functions.get-media-url]
verify_jwt = true

[functions.cleanup-expired-calls]
verify_jwt = false

[functions.cleanup-inactive-tokens]
verify_jwt = false
